export const countryCodes: { [index: string]: string } = {
  Andorra: 'AD',
  'The United Arab Emirates': 'AE',
  Afghanistan: 'AF',
  'Antigua And Barbuda': 'AG',
  Anguilla: 'AI',
  Albania: 'AL',
  Armenia: 'AM',
  Angola: 'AO',
  Antarctica: 'AQ',
  Argentina: 'AR',
  'American Samoa': 'AS',
  Austria: 'AT',
  Australia: 'AU',
  Aruba: 'AW',
  'Aland Islands': 'AX',
  Azerbaijan: 'AZ',
  'Bosnia And Herzegovina': 'BA',
  Barbados: 'BB',
  Bangladesh: 'BD',
  Belgium: 'BE',
  'Burkina Faso': 'BF',
  Bulgaria: 'BG',
  Bahrain: 'BH',
  Burundi: 'BI',
  Benin: 'BJ',
  Bermuda: 'BM',
  'Brunei Darussalam': 'BN',
  Bolivia: 'BO',
  Bonaire: 'BQ',
  Brazil: 'BR',
  'The Bahamas': 'BS',
  Bhutan: 'BT',
  Botswana: 'BW',
  Belarus: 'BY',
  Belize: 'BZ',
  Canada: 'CA',
  'The Cocos Keeling Islands': 'CC',
  'The Democratic Republic Of The Congo': 'CD',
  'The Central African Republic': 'CF',
  'The Congo': 'CG',
  Switzerland: 'CH',
  'Coted Ivoire': 'CI',
  'The Cook Islands': 'CK',
  Chile: 'CL',
  Cameroon: 'CM',
  China: 'CN',
  Colombia: 'CO',
  'Costa Rica': 'CR',
  Cuba: 'CU',
  'Cabo Verde': 'CV',
  Curacao: 'CW',
  'Christmas Island': 'CX',
  Cyprus: 'CY',
  Czechia: 'CZ',
  Germany: 'DE',
  Djibouti: 'DJ',
  Denmark: 'DK',
  Dominica: 'DM',
  'The Dominican Republic': 'DO',
  Algeria: 'DZ',
  Ecuador: 'EC',
  Estonia: 'EE',
  Egypt: 'EG',
  Eritrea: 'ER',
  Spain: 'ES',
  Ethiopia: 'ET',
  Finland: 'FI',
  Fiji: 'FJ',
  'The Falkland Islands Malvinas': 'FK',
  'Federated States Of Micronesia': 'FM',
  'The Faroe Islands': 'FO',
  France: 'FR',
  Gabon: 'GA',
  'The United Kingdom Of Great Britain And Northern Ireland': 'GB',
  Grenada: 'GD',
  Georgia: 'GE',
  'French Guiana': 'GF',
  Guernsey: 'GG',
  Ghana: 'GH',
  Gibraltar: 'GI',
  Greenland: 'GL',
  'The Gambia': 'GM',
  Guinea: 'GN',
  Guadeloupe: 'GP',
  'Equatorial Guinea': 'GQ',
  Greece: 'GR',
  Guatemala: 'GT',
  Guam: 'GU',
  'Guinea Bissau': 'GW',
  Guyana: 'GY',
  'Hong Kong': 'HK',
  Honduras: 'HN',
  Croatia: 'HR',
  Haiti: 'HT',
  Hungary: 'HU',
  Indonesia: 'ID',
  Ireland: 'IE',
  Israel: 'IL',
  'Isle Of Man': 'IM',
  India: 'IN',
  'British Indian Ocean Territory': 'IO',
  Iraq: 'IQ',
  'Islamic Republic Of Iran': 'IR',
  Iceland: 'IS',
  Italy: 'IT',
  Jamaica: 'JM',
  Jordan: 'JO',
  Japan: 'JP',
  Kenya: 'KE',
  Kyrgyzstan: 'KG',
  Cambodia: 'KH',
  Kiribati: 'KI',
  'The Comoros': 'KM',
  'Saint Kitts And Nevis': 'KN',
  'The Democratic Peoples Republic Of Korea': 'KP',
  'The Republic Of Korea': 'KR',
  Kuwait: 'KW',
  'The Cayman Islands': 'KY',
  Kazakhstan: 'KZ',
  'The Lao Peoples Democratic Republic': 'LA',
  Lebanon: 'LB',
  'Saint Lucia': 'LC',
  Liechtenstein: 'LI',
  'Sri Lanka': 'LK',
  Liberia: 'LR',
  Lesotho: 'LS',
  Lithuania: 'LT',
  Luxembourg: 'LU',
  Latvia: 'LV',
  Libya: 'LY',
  Morocco: 'MA',
  Monaco: 'MC',
  'The Republic Of Moldova': 'MD',
  Montenegro: 'ME',
  Madagascar: 'MG',
  'The Marshall Islands': 'MH',
  'Republic Of North Macedonia': 'MK',
  Mali: 'ML',
  Myanmar: 'MM',
  Mongolia: 'MN',
  Macao: 'MO',
  Martinique: 'MQ',
  Mauritania: 'MR',
  Montserrat: 'MS',
  Malta: 'MT',
  Mauritius: 'MU',
  Maldives: 'MV',
  Malawi: 'MW',
  Mexico: 'MX',
  Malaysia: 'MY',
  Mozambique: 'MZ',
  Namibia: 'NA',
  'New Caledonia': 'NC',
  'The Niger': 'NE',
  Nigeria: 'NG',
  Nicaragua: 'NI',
  'The Netherlands': 'NL',
  Norway: 'NO',
  Nepal: 'NP',
  Nauru: 'NR',
  Niue: 'NU',
  'New Zealand': 'NZ',
  Oman: 'OM',
  Panama: 'PA',
  Peru: 'PE',
  'French Polynesia': 'PF',
  'Papua New Guinea': 'PG',
  'The Philippines': 'PH',
  Pakistan: 'PK',
  Poland: 'PL',
  'Saint Pierre And Miquelon': 'PM',
  'Puerto Rico': 'PR',
  'State Of Palestine': 'PS',
  Portugal: 'PT',
  Palau: 'PW',
  Paraguay: 'PY',
  Qatar: 'QA',
  Reunion: 'RE',
  Romania: 'RO',
  Serbia: 'RS',
  'The Russian Federation': 'RU',
  Rwanda: 'RW',
  'Saudi Arabia': 'SA',
  'Solomon Islands': 'SB',
  Seychelles: 'SC',
  'The Sudan': 'SD',
  Sweden: 'SE',
  Singapore: 'SG',
  'Ascension And Tristan Da Cunha Saint Helena': 'SH',
  Slovenia: 'SI',
  'Svalbard And Jan Mayen': 'SJ',
  Slovakia: 'SK',
  'Sierra Leone': 'SL',
  'San Marino': 'SM',
  Senegal: 'SN',
  Somalia: 'SO',
  Suriname: 'SR',
  'South Sudan': 'SS',
  'Sao Tome And Principe': 'ST',
  'El Salvador': 'SV',
  'Syrian Arab Republic': 'SY',
  Eswatini: 'SZ',
  'The Turks And Caicos Islands': 'TC',
  Chad: 'TD',
  'The French Southern Territories': 'TF',
  Togo: 'TG',
  Thailand: 'TH',
  Tajikistan: 'TJ',
  'Timor Leste': 'TL',
  Turkmenistan: 'TM',
  Tunisia: 'TN',
  Tonga: 'TO',
  Türkiye: 'TR',
  'Trinidad And Tobago': 'TT',
  Tuvalu: 'TV',
  'Taiwan, Republic Of China': 'TW',
  'United Republic Of Tanzania': 'TZ',
  Ukraine: 'UA',
  Uganda: 'UG',
  'The United States Minor Outlying Islands': 'UM',
  'The United States Of America': 'US',
  Uruguay: 'UY',
  Uzbekistan: 'UZ',
  'The Holy See': 'VA',
  'Saint Vincent And The Grenadines': 'VC',
  'Bolivarian Republic Of Venezuela': 'VE',
  'British Virgin Islands': 'VG',
  'US Virgin Islands': 'VI',
  Vietnam: 'VN',
  Vanuatu: 'VU',
  'Wallis And Futuna': 'WF',
  Kosovo: 'XK',
  Yemen: 'YE',
  Mayotte: 'YT',
  'South Africa': 'ZA',
  Zambia: 'ZM',
  Zimbabwe: 'ZW',
}
